### ISSUE TITLE
升级14，wifi无法使用

### ISSUE THREAD

**Issue by kittyzero520** [XiangNorth/Matebook-14-2019-Hackintosh#1]
升级14正式版，wifi不可以使用，无法设置

**Comment by withxat** [comment]
目前 Sonoma(macOS 14) 的 Intel Wi-Fi 驱动还在开放中，实在要用可以去下载内测版本，我尝试过没有太大 Bug，Sonoma beta 5+ 的驱动在这里 [itlwm/issues#833](https://github.com/OpenIntelWireless/itlwm/issues/883#issuecomment-1670749680) ，beta 4 及之前的往上翻也有，直接替换 `EFI/OC/KEXT` 下的 `AirportItlwm.kext` 就好了。

顺便一提我这里尝试升级到 Sonoma 后蓝牙过段时间也会抽风坏掉，所以退回来了，估计还需要适配。

**Comment by withxat** [comment]
嗷，没看到你是正式版，那应该直接用发的 beta 5+ 那个替换就好了。

**Comment by kittyzero520** [comment]
可以用了，但是每次开机会提示，异常关机

**Comment by kittyzero520** [comment]
Update 2023.8.9

Support Sonoma beta 5+

It's the first time I've seen API interfaces modified in the same macOS major version.
Don't use it on Sonoma beta 4 and below !!!

[AirportItlwm-Sonoma-Preview05.zip](https://github.com/OpenIntelWireless/itlwm/files/12299048/AirportItlwm-Sonoma-Preview05.zip)


下载中这个对吧

**Comment by kittyzero520** [comment]
发下一个问题，进度条加载到30%就黑屏10分钟才可以进行系统登录界面

**Comment by withxat** [comment]
> 发下一个问题，进度条加载到30%就黑屏10分钟才可以进行系统登录界面

在`boot-arg`里加入`-igfxblt`和`-igfxbls`
这个是 Sonoma 才有的显卡适配 Bug

涉及这个项目 [WhateverGreen](https://github.com/acidanthera/WhateverGreen)

**Comment by withxat** [comment]
> Update 2023.8.9
> 
> 
> 
> Support Sonoma beta 5+
> 
> 
> 
> It's the first time I've seen API interfaces modified in the same macOS major version.
> 
> Don't use it on Sonoma beta 4 and below !!!
> 
> 
> 
> [AirportItlwm-Sonoma-Preview05.zip](https://github.com/OpenIntelWireless/itlwm/files/12299048/AirportItlwm-Sonoma-Preview05.zip)
> 
> 
> 
> 
> 
> 下载中这个对吧

是的
