### ISSUE TITLE
你好，现在还可以升级到15不

### ISSUE THREAD

**Issue by kittyzero520** [XiangNorth/Matebook-14-2019-Hackintosh#2]
目前是14.0,可以直接升级到15吗？

**Comment by withxat** [comment]
🧐 建议是不要，很多 kext 可能要更新一下，等我晚上测试一下发个新版哈。

**Comment by kittyzero520** [comment]
电脑很热，不知道你是不是也一样，是不是要清理灰尘了

**Comment by kittyzero520** [comment]
发现一个cpu不是i5的efi

**Comment by kittyzero520** [comment]
https://github.com/KevinamdKim/Matebook14-2019-Hackintosh-Sequoia15.0

**Comment by withxat** [comment]
i5 和 i7 不影响 efi 正常启动，可以试试，我这边看到 itlwm 还没有主动适配 Sequoia，似乎还有些 Bug 
OpenIntelWireless/itlwm#983

他的 efi 还是用的 2.3.0 itlwm，可能会导致 Wi-Fi 启动不起来，如果要升级可以下一个 HeliPort 备用，看上面的评论说可以通过这个 App 暂时启用并连接 Wi-Fi：
https://github.com/diepeterpan/HeliPort/releases/tag/v1.5.0

我的电脑现在也经常性发热，前段时间清灰过一次，但好像也没什么效果，也可能是苹果重点到 M 系列芯片上去了，Intel 的体验就不可抗力下降了，我个人是降级到 13 一直用着的

**Comment by withxat** [comment]
@kittyzero520 看起来他还用了一个修复蓝牙的 kext，我这个可能升上去就没蓝牙了，要升级的话切换成他的 efi 升级吧。

**Comment by withxat** [comment]
简单整理了一下现有的 EFI，目前本 EFI 还是只针对 Ventura(^13.0)，之后会提供升级到更高版本的一些引导，在上游有更完善稳定的对 Sequoia(^15.0) 支持之前，不会有版本更替的改动。

Sonoma(^14.0) 系请参考： [andrewlsa/Matebook14-2019-Hackintosh](https://github.com/andrewlsa/Matebook14-2019-Hackintosh)
Sequoia(^15.0) 系请参考：[KevinamdKim/Matebook14-2019-Hackintosh-Sequoia15.0](https://github.com/KevinamdKim/Matebook14-2019-Hackintosh-Sequoia15.0)

---

I’ve organized the current EFI setup, which is still focused on Ventura (^13.0). I’ll provide guides for upgrading to higher versions later, but there won’t be any changes until upstream support for Sequoia (^15.0) is more stable and complete.

For the Sonoma (^14.0) series, check out: [andrewlsa/Matebook14-2019-Hackintosh](https://github.com/andrewlsa/Matebook14-2019-Hackintosh)  
For the Sequoia (^15.0) series, refer to: [KevinamdKim/Matebook14-2019-Hackintosh-Sequoia15.0](https://github.com/KevinamdKim/Matebook14-2019-Hackintosh-Sequoia15.0)
